name: Deploy Terraform
description: Pick which Terraform modules to deploy
title: "Deploy: <env>"
labels: [deploy-request]

body:
  - type: checkboxes
    id: modules
    attributes:
      label: Select modules
      description: Choose one or more modules to deploy
      options:
        - label: mod_a
        - label: mod_b
        - label: mod_c
        # To pre-check options, add `default: true` under the option itself.
        # e.g. - label: mod_a
        #         default: true

  - type: dropdown
    id: env
    attributes:
      label: Target environment
      options:
        - dev
        - prod
      default: 0   # 👈 must live inside attributes, integer index (0=dev, 1=prod)

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Any extra context for this deployment
