name: Deploy Terraform
description: Pick which Terraform modules to deploy
title: "Deploy: <env>"
labels: [deploy-request]

body:
  - type: checkboxes
    id: modules
    attributes:
      label: Select modules
      description: Choose one or more modules to deploy
      options:
        - label: mod_a
        - label: mod_b
        - label: mod_c
    # To pre-check some options, add `default: true` to the specific option(s) above.
    # e.g.  - label: mod_a
    #         default: true

  - type: dropdown
    id: env
    attributes:
      label: Target environment
      options:
        - dev
        - prod
    default: 0   # 0 = dev, 1 = prod   <-- must be an integer

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Any extra context for this deployment
