# name: cicd_test
# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'infrastructure/terraform/source/**'
#       - '.github/workflows/main.yaml'
# jobs:
#   build:
#     if: "!contains(github.event.head_commit.message, 'skip ci')"
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: 1.0.7
#       - name: Install CI Deps
#         run: |
#           sudo apt-get install build-essential
#           pip install python3
#       - name:  Apply Terraform and Sync Databricks IAM
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
# #           make init
# #           make apply
# #           make init_persistent_store_client
# #           make apply_persistent_store_client
# #           make databricks-instance-profile-sync